### ISSUE TITLE
AuctionBot threads initialization error.

### ISSUE THREAD

**Issue by selective-yt** [Exortions/skyblock-2.0#161]
```
[05:38:58 INFO]: Server permissions file permissions.yml is empty, ignoring it
[05:38:59 INFO]: Done (14.989s)! For help, type "help" or "?"
[05:38:59 INFO]: [Citizens] Loaded 217 NPCs.
[05:38:59 INFO]: [ActionBarAPI] No update was found, you are running the latest version.
[05:39:00 INFO]: [SB] Starting auction bot...
[05:39:08 INFO]: [SB] Queued 20 threads for the Auction Bot, containing 1000 auctions in page 2 of the Hypixel API.
[05:39:08 WARN]: Exception in thread "Craft Scheduler Thread - 6"
.
.
.
[05:39:08 WARN]: org.apache.commons.lang.UnhandledException: Plugin Skyblock v1.0.0 generated an exception while executing task 1336
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.skyblock.skyblock.features.auction.bot.AuctionBot$1AuctionBotThread.run(AuctionBot.java:157)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
.
.
.
[05:39:09 INFO]: [SB] Queued 20 threads for the Auction Bot, containing 1000 auctions in page 1 of the Hypixel API.
[05:39:09 WARN]: Exception in thread "Craft Scheduler Thread - 22"
[05:39:09 WARN]: org.apache.commons.lang.UnhandledException: Plugin Skyblock v1.0.0 generated an exception while executing task 635
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(Unknown Source)
        at java.util.HashMap$ValueIterator.next(Unknown Source)
        at com.skyblock.skyblock.features.auction.AuctionHouse$4.run(AuctionHouse.java:294)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by Exortions** [comment]
Interesting. are you sure you installed everything correctly (with the entire dependencies folder)?

**Comment by OptimusChen** [comment]
ConcurrentModificationException is a known issue that should be fixed now. Don't know about the other one
