### ISSUE TITLE
Bugs I experienced (I may have messed up the build, but idunno)

### ISSUE THREAD

**Issue by Hanuko33** [Exortions/skyblock-2.0#178]
Mobs spawning eggs don't spawn skyblock mobs,
Dragon in dragon den breaks blocks (I don't think it shuold),
I couldn't do any damage to the dragon (I had aotd, both ability and mele didn't work),
Needs op, for almost everything,
Empty bazaar,
Why are there things in ah (I didn't put them)?
I have 16 gigs of ram (8 allocated to the server, 2 to the client) and i7 intel processor (I think my pc isn't that bad), but chunks don't load properly (slow),
There's lava in the portal entrance (the thing you go in, and it moves you to another island) of nether fortress,
My island didn't generate (there was only jerry, that wasn't rendering).

Those bugs were found in very short period of time.

Hopefully those can be fixed in code, or something in my local server can be changed. 
I followed the guide for install.

**Comment by Hanuko33** [comment]
Minions don't work:
[19:56:24 ERROR]: Could not pass event BlockPlaceEvent to Skyblock v1.0.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:127) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:158) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:503) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_392]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_392]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
Caused by: java.lang.NoClassDefFoundError: org/reflections/Reflections
	at com.skyblock.skyblock.listeners.BlockListener.onBlockPlace(BlockListener.java:52) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
	... 18 more

**Comment by Hanuko33** [comment]
This:
![2023-12-10_20 00 26](https://github.com/Exortions/skyblock-2.0/assets/93970656/cb3b2cfb-8b79-4781-b77f-51d19a5f4d33)
(no hp)

**Comment by Hanuko33** [comment]
While trying to test the dragon, dragons have no limit, the dragon flied out of end island and went to the spider island.

Also why?:
![2023-12-10_20 03 52](https://github.com/Exortions/skyblock-2.0/assets/93970656/653cd82a-e655-44a5-8b18-291b373cb9a5)

"Cannot summon dragon: Gate schematic not found or corrupted!" (spawns dragon anyways)

**Comment by Hanuko33** [comment]
While fighting dragon:
[20:06:08 WARN]: [SB] Task #14526 for Skyblock v1.0.0 generated an exception
java.lang.NoClassDefFoundError: xyz/xenondevs/particle/ParticleEffect
	at com.skyblock.skyblock.features.items.weapons.AspectOfTheDragons$1.run(AspectOfTheDragons.java:108) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-741a1bd]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]

also, no reward after killing dragon (i did /kill cause it literally doesn't take dmg)

**Comment by Hanuko33** [comment]
When breaking wheat, no seed drop

Missing minion:
![2023-12-10_20 09 28](https://github.com/Exortions/skyblock-2.0/assets/93970656/7d4dd324-50de-4f52-ac4d-249bc522f835)

okay?:

**Comment by Hanuko33** [comment]
misclick, anyways:
![Uploading 2023-12-10_20.11.56.png…]()

**Comment by Hanuko33** [comment]
missing text
![2023-12-10_20 11 56](https://github.com/Exortions/skyblock-2.0/assets/93970656/03fa13e1-81f1-4997-84ff-bc6194014237)
![2023-12-10_20 14 03](https://github.com/Exortions/skyblock-2.0/assets/93970656/dd54e805-90e7-49e6-a528-ae88f61b6b4d)

**Comment by Hanuko33** [comment]
Idea: add /addcoin & /changetime (or smth) commands

**Comment by Hanuko33** [comment]
blacksmith doesn't work =(
