### ISSUE TITLE
Error while enabling the plugin

### ISSUE THREAD

**Issue by erenforger** [Exortions/skyblock-2.0#187]
Hey i am getting this error while loading the plugin
Error occurred while enabling Skyblock v1.0.0 (Is it up to date?)
java.lang.NullPointerException: null
    at com.skyblock.skyblock.utilities.Util.spawnSkyblockNpc(Util.java:483) ~[?:?]
    at com.skyblock.skyblock.features.merchants.Merchant.createNpc(Merchant.java:94) ~[?:?]
    at com.skyblock.skyblock.Skyblock.registerMerchants(Skyblock.java:687) ~[?:?]
    at com.skyblock.skyblock.Skyblock.onEnable(Skyblock.java:188) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[01:36:14] [Server thread/INFO]: [SB] Disabling Skyblock v1.0.0

**Comment by Ankush19557** [comment]
@Exortions help me please
