### ISSUE TITLE
Trouble running

### ISSUE THREAD

**Issue by UltraBlackLinux** [Exortions/skyblock-2.0#21]
Hey there,
I just tried to run this on paper 1.8.8 (Could you add viaversion by default?), but I'm facing some issues:
```
[17:36:24 INFO]: [SB] Initializing items...

[17:36:24 ERROR]: Error occurred while enabling Skyblock v1.0.0 (Is it up to date?)
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at com.skyblock.skyblock.utilities.item.ItemHandler.init(ItemHandler.java:95) ~[?:?]
	at com.skyblock.skyblock.Skyblock.initializeNEUItems(Skyblock.java:681) ~[?:?]
	at com.skyblock.skyblock.Skyblock.onEnable(Skyblock.java:145) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
[17:36:24 INFO]: [SB] Disabling Skyblock v1.0.0
[17:36:24 INFO]: [SB] Disabling Skyblock...

[17:36:24 ERROR]: Error occurred while disabling Skyblock v1.0.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.skyblock.skyblock.features.fairysouls.FairySoulHandler.killAllSouls()" because "this.fairySoulHandler" is null
	at com.skyblock.skyblock.Skyblock.onDisable(Skyblock.java:179) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
```
Any idea about this? Trying to join spams `An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Unable to access address of buffer` into the console. Same errors appear on Spigot.
I would love to try this plugin!

**Comment by Exortions** [comment]
go to dependencies/skyblock/items, and drag all of them into <server>/plugins/Skyblock/items.

**Comment by Exortions** [comment]
Viaversion is slightly buggy with Skyblock, we will try fixing that later.

Also note that our version of Skyblock is hardly complete, and it isn't very playable. Come back in maybe a month for a playable gameplay experience, as currently there are lots of bugs and unimplemented features.

**Comment by Exortions** [comment]
(items folder: https://github.com/Exortions/skyblock-2.0/tree/master/dependencies/skyblock/items)

**Comment by Exortions** [comment]
Also if you get any issues with private islands, delete the private_island.schematic file and copy it from `dependencies/skyblock/private_island.schematic`, for some reason it is corrupted when it pulls.

**Comment by UltraBlackLinux** [comment]
> go to dependencies/skyblock/items, and drag all of them into /plugins/Skyblock/items.

I copied all of the contentents of the dependency directory right into the server root. Multiple times

**Comment by Exortions** [comment]
nono, just copy everything in the ITEMS folder into <plugins folder>/Skyblock/items. (also private_island.schematic).

As you can see, it pulls everything else on its own:
![image](https://user-images.githubusercontent.com/75327059/208322207-c09bc305-6695-44b4-b06f-12dd58c92c06.png)

**Comment by UltraBlackLinux** [comment]
> nono, just copy everything in the ITEMS folder into /Skyblock/items. (also private_island.schematic).
> 
> As you can see, it pulls everything else on its own: ![image](https://user-images.githubusercontent.com/75327059/208322207-c09bc305-6695-44b4-b06f-12dd58c92c06.png)

oh well. 

Also fixed the bukkit error. Needed to run it with java 8
