### ISSUE TITLE
PlayerJoinEvent failing

### ISSUE THREAD

**Issue by UltraBlackLinux** [Exortions/skyblock-2.0#22]
Just got this error when joining. I assume I should be teleported, because instead I spawn, fall into the void, the chat gets spammed with the according message, but I never die:
```
[22:28:20 ERROR]: Could not pass event PlayerJoinEvent to Skyblock v1.0.0
org.bukkit.event.EventException: null
Caused by: java.lang.NullPointerException
	at com.skyblock.skyblock.features.island.IslandManager.createIsland(IslandManager.java:54) ~[?:?]
	at com.skyblock.skyblock.listeners.PlayerJoinListener.createIsland(PlayerJoinListener.java:23) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_352]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_352]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_352]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_352]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
	... 14 more
```
Can you fix this?

Edit: I see. This is the schematic problem you were talking about. I needed to manually replace the schematic file after the server started and before any player joined

Dumb workaround:

```
#!/usr/bin/bash
$(sleep 7; cp ../dependencies/skyblock/private_island.schematic plugins/Skyblock/private_island.schematic)&
/usr/lib/jvm/zulu-8/bin/java -Xms4G -Xmx4G -jar spigot-1.8.8-R0.1-SNAPSHOT-latest.jar
```

**Comment by Exortions** [comment]
try /warp hub, hasn't happened to me before

**Comment by Exortions** [comment]
nvm, delete the world called `island-<uuid>`, and re-log in.

**Comment by Exortions** [comment]
Yeah, about the schematic, I have zero clue why it's corrupted when it pulls from GitHub. The file on GitHub isn't corrupted at all, but when the DependencyUpdater pulls it gets corrupted.
