### ISSUE TITLE
mod wont load

### ISSUE THREAD

**Issue by bruh521** [Exortions/skyblock-2.0#83]
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_321]
        at com.skyblock.skyblock.utilities.item.ItemHandler.init(ItemHandler.java:108) ~[?:?]
        at com.skyblock.skyblock.Skyblock.initializeNEUItems(Skyblock.java:849) ~[?:?]
        at com.skyblock.skyblock.Skyblock.onEnable(Skyblock.java:182) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_321]

**Comment by Exortions** [comment]
drag the `items` folder (located at https://github.com/Exortions/skyblock-2.0/tree/master/dependencies/skyblock/) into
`<plugins folder>/Skyblock/items`

drag the `mobLoot` folder (located at https://github.com/Exortions/skyblock-2.0/tree/master/dependencies/skyblock/) into `<plugins folder>/Skyblock/items`

also, make sure you have both the `world` and `deep_caverns` world installed on your server (located at https://github.com/Exortions/skyblock-2.0/tree/master/dependencies)
